# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
