# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0002_event_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maxIsBetter',
            field=models.BooleanField(default=True),
        ),
    ]
