# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=10)),
                ('feePayable', models.IntegerField(default=100)),
                ('feePaid', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 2, 44, 31, 948176))),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.College')),
                ('registeredBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
