# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20161123_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
