# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_eventresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='score',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
