# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20161207_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='nextRoundEligibility',
            field=models.BooleanField(default=False),
        ),
    ]
