# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_eventresult_nextroundeligibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresult',
            name='status',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
