# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170204_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.EventRegistration'),
        ),
    ]
