# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0012_auto_20170204_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='scoreSubmittedBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
