# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_eventresult_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='teamName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
