# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_eventregistration_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='feePaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='feePaid',
            field=models.BooleanField(default=False),
        ),
    ]
