# Generated by Django 2.0.1 on 2018-02-08 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20170204_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.College'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registeredBy',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'registrar'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventman.Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registeredBy',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'registrar'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='scoreSubmittedBy',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'coordinator'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registration.EventRegistration'),
        ),
    ]
