# Generated by Django 2.0.1 on 2018-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20180209_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='feePayable',
            field=models.IntegerField(default=20),
        ),
    ]
