# Generated by Django 2.0.2 on 2018-02-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_campusambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='refferedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.CampusAmbassador'),
        ),
    ]
