# Generated by Django 2.0.1 on 2018-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
